language: java

jdk:
  - oraclejdk11

env:
  global:
    - DEFOLD_AUTH=foobar
    - DEFOLD_USER=john.doe@gmail.com

script: |
    echo Add other actions to build,
    export CHANNEL="alpha"
    export BUILD_SERVER="https://build-stage.defold.com"
    export PLATFORMS="js-web,x86-win32,x86_64-win32,x86_64-linux,x86_64-darwin,armv7-darwin,armv7-android,arm64-android"
    export PROJECTS="https://github.com/defold/extension-webview/archive/master.zip, https://github.com/defold/extension-fbinstant/archive/master.zip, https://github.com/defold/extension-html5/archive/master.zip, https://github.com/defold/extension-facebook/archive/master.zip, https://github.com/defold/extension-push/archive/master.zip, https://github.com/defold/extension-firebase-core/archive/master.zip, https://github.com/defold/extension-gpgs/archive/master.zip"
    ./run-tests.sh
