name: CI

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 2 * * *

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '11.0.1'
        architecture: x64
    - name: Run tests
      run: |
        export CHANNEL="alpha"
        export BUILD_SERVER="https://build-stage.defold.com"
        export PLATFORMS="js-web,x86-win32,x86_64-win32,x86_64-linux,x86_64-darwin,armv7-darwin,armv7-android,arm64-android"
        export PROJECTS="https://github.com/defold/extension-webview/archive/master.zip"
        export PROJECTS="${PROJECTS}, https://github.com/defold/extension-fbinstant/archive/master.zip"
        export PROJECTS="${PROJECTS}, https://github.com/defold/extension-html5/archive/master.zip"
        export PROJECTS="${PROJECTS}, https://github.com/defold/extension-facebook/archive/master.zip"
        export PROJECTS="${PROJECTS}, https://github.com/defold/extension-push/archive/master.zip"
        export PROJECTS="${PROJECTS}, https://github.com/defold/extension-firebase-core/archive/master.zip"
        export PROJECTS="${PROJECTS}, https://github.com/defold/extension-gpgs/archive/master.zip"
        export PROJECTS="${PROJECTS}, https://github.com/defold/extension-firebase-analytics/archive/master.zip"
        export PROJECTS="${PROJECTS}, https://github.com/defold/extension-videoplayer-native/archive/master.zip"
        export PROJECTS="${PROJECTS}, https://github.com/defold/extension-adinfo/archive/master.zip"
        export PROJECTS="${PROJECTS}, https://github.com/defold/extension-iac/archive/master.zip"
        export PROJECTS="${PROJECTS}, https://github.com/defold/extension-iap/archive/master.zip"
        export PROJECTS="${PROJECTS}, https://github.com/britzl/defold-screenshot/archive/master.zip"
        export PROJECTS="${PROJECTS}, https://github.com/britzl/defold-luasec/archive/master.zip"
        export PROJECTS="${PROJECTS}, https://github.com/britzl/defold-sharing/archive/master.zip"
        export PROJECTS="${PROJECTS}, https://github.com/subsoap/defos/archive/master.zip"
        export PROJECTS="${PROJECTS}, https://github.com/AGulev/DefVideoAds/archive/master.zip"
        export PROJECTS="${PROJECTS}, https://github.com/Lerg/extension-admob/archive/master.zip"
        export PROJECTS="${PROJECTS}, https://github.com/Lerg/extension-directories/archive/master.zip"
        export PROJECTS="${PROJECTS}, https://github.com/dapetcu21/defold-fmod/archive/master.zip"
        export PROJECTS="${PROJECTS}, https://github.com/GameAnalytics/GA-SDK-DEFOLD/archive/master.zip"
        ./run-tests.sh
    - name: Notify if tests failed
      uses: homoluctus/slatify@master
      if: failure()
      with:
        type: ${{ job.status }}
        job_name: 'SDK tests'
        channel: '#defold-alarms-build'
        url: ${{ secrets.SLACK_WEBHOOK }}
      
      
