name: CI

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 2 * * *
  
  
jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 1
            matrix:
                projects: [
                    "https://github.com/Lerg/extension-admob/archive/master.zip",
                    "https://github.com/Lerg/extension-directories/archive/master.zip",
                    "https://github.com/dapetcu21/defold-fmod/archive/master.zip",
                    "https://github.com/GameAnalytics/GA-SDK-DEFOLD/archive/master.zip"
                ]
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-java@v1
              with:
                java-version: '11.0.1'
                architecture: x64
            - name: Run tests (alpha)
              run: ./run-tests.sh
              env:
                CHANNEL: "alpha"
                BUILD_SERVER: "https://build-stage.defold.com"
                PLATFORMS: "js-web,x86_64-win32,x86_64-linux,x86_64-darwin,armv7-darwin,armv7-android"
                PROJECTS: ${{ matrix.projects }}
            - name: Run tests (beta)
              run: ./run-tests.sh
              env:
                CHANNEL: "beta"
                BUILD_SERVER: "https://build-stage.defold.com"
                PLATFORMS: "js-web,x86_64-win32,x86_64-linux,x86_64-darwin,armv7-darwin,armv7-android"
                PROJECTS: ${{ matrix.projects }}
            - name: Notify if tests failed
              uses: homoluctus/slatify@master
              if: failure()
              with:
                type: ${{ job.status }}
                job_name: 'SDK tests'
                channel: '#defold-alarms-build'
                url: ${{ secrets.SLACK_WEBHOOK }}

    test-stable:
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 1
            matrix:
                projects: [
                    "https://github.com/Lerg/extension-admob/archive/master.zip",
                    "https://github.com/Lerg/extension-directories/archive/master.zip",
                    "https://github.com/dapetcu21/defold-fmod/archive/master.zip",
                    "https://github.com/GameAnalytics/GA-SDK-DEFOLD/archive/master.zip"
                ]
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-java@v1
              with:
                java-version: '11.0.1'
                architecture: x64
            - name: Run tests (stable)
              run: ./run-tests.sh
              env:
                CHANNEL: "stable"
                BUILD_SERVER: "https://build-stage.defold.com"
                PLATFORMS: "js-web,x86_64-win32,x86_64-linux,x86_64-darwin,armv7-darwin,armv7-android"
                PROJECTS: ${{ matrix.projects }}
            - name: Notify if tests failed
              uses: homoluctus/slatify@master
              if: failure()
              with:
                type: ${{ job.status }}
                job_name: 'SDK tests'
                channel: '#defold-alarms-build'
                url: ${{ secrets.SLACK_WEBHOOK }}
