name: "test"

on:
  push:
    branches:
      - master

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 2
            matrix:
              projects: [
                  "https://github.com/defold/extension-adinfo/archive/master.zip",
                  "https://github.com/defold/extension-facebook/archive/master.zip",
                  "https://github.com/defold/extension-fbinstant/archive/master.zip",
                ]
        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-java@v3
              with:
                java-version: '17.0.5+8'
                architecture: x64
                distribution: 'temurin'

            - name: Run tests
              run: ./run-tests.sh
              env:
                CHANNEL: "beta"
                BUILD_SERVER: "https://build-stage.defold.com"
                PLATFORMS: "x86_64-linux"
                PROJECTS: ${{ matrix.projects }}
            - name: Notify if tests failed
              if: failure()
              run: echo "OH NO"