name: CI

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 2 * * *

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '11.0.1'
        architecture: x64
    - name: Run tests
      run: |
        export CHANNEL="alpha"
        export BUILD_SERVER="https://build-stage.defold.com"
        export PLATFORMS="js-web,x86-win32,x86_64-win32,x86_64-linux,x86_64-darwin,armv7-darwin,armv7-android,arm64-android"
        export PROJECTS="https://github.com/defold/extension-webview/archive/master.zip"
        export PROJECTS="${PROJECTS}, https://github.com/defold/extension-fbinstant/archive/master.zip"
        export PROJECTS="${PROJECTS}, https://github.com/defold/extension-html5/archive/master.zip"
        export PROJECTS="${PROJECTS}, https://github.com/defold/extension-facebook/archive/master.zip"
        export PROJECTS="${PROJECTS}, https://github.com/defold/extension-push/archive/master.zip"
        export PROJECTS="${PROJECTS}, https://github.com/defold/extension-firebase-core/archive/master.zip"
        export PROJECTS="${PROJECTS}, https://github.com/defold/extension-gpgs/archive/master.zip"
        export PROJECTS="${PROJECTS}, https://github.com/defold/extension-firebase-analytics/archive/master.zip"
        export PROJECTS="${PROJECTS}, https://github.com/subsoap/defos/archive/master.zip"
        export PROJECTS="${PROJECTS}, https://github.com/AGulev/DefVideoAds/archive/master.zip"
        export PROJECTS="${PROJECTS}, https://github.com/Lerg/extension-admob/archive/master.zip"
        ./run-tests.sh

  notify:
    steps:
    - name: Notify failed tests
      if: jobs.test.status == "failure"
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      uses: Ilshidur/action-slack@master
      with:
        args: 'SDK tests failed'
      
      
